<h2 id="mymenu" class="menu">
  <a href="index.php" id="home" style="font-size:22px">Home</a>
  <a href="jobs.php" id="jobs" style="font-size:22px">Jobs</a>
  <a href="apply.php" id="application" style="font-size:22px">Apply</a>
  <a href="about.php" id="about" style="font-size:22px">About</a>
  <a href="enhancements.php" id="enhancements" style="font-size:22px">Enhancements</a>
  <a href="enhancements2.php" id="enhancements" style="font-size:22px">EnhancementsJS</a>
  <a href="manager.php" id="manager" style="font-size:22px">Manager</a>
  <a href="phpenhancements.php" id="phpenhancement" style="font-size:22px">EnhancementsPHP</a>
</h2>